name: Scheduled Version Analysis

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  analyze-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Analysis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/config.yaml:/app/config.yaml \
            -v ${{ github.workspace }}/output:/app/output \
            opsclub/terraform-providers-versions:main \
            --html-output /app/output/report.html \
            --markdown-output /app/output/report.md

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: |
            output/report.html
            output/report.md
          retention-days: 90

      - name: Create Issue on Version Changes
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('output/report.md', 'utf8');
            if (report.includes('Version changes detected')) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🔄 Terraform Version Changes Detected',
                body: report,
                labels: ['version-changes', 'automated']
              });
            }